// MIGRATED: inc/custom-header.php -> components/CustomHeader.tsx
// This file replaces the WordPress custom header feature (add_theme_support('custom-header'),
// _s_custom_header_setup(), and _s_header_style()) with a React component that:
// - Fetches the custom header image from the WP REST API
// - Renders the header image using Next.js <Image> component
// - Applies text color styles via inline styles or CSS variables
// - Replaces the_header_image_tag() with an <Image> component

// TODO: Manual review needed -- WordPress custom header text color settings are stored in
// the Customizer (get_header_textcolor()). Expose these via /wp-json/wp/v2/settings or
// a custom REST endpoint if dynamic color control is required.

// TODO: Manual review needed -- Add your WordPress domain to next.config.js under
// images.remotePatterns to allow Next.js Image optimization for WP media URLs.

import Image from 'next/image';
import { CSSProperties } from 'react';

// TypeScript types for WordPress custom header data from REST API
interface WordPressHeaderImageData {
  url: string;
  thumbnail_url: string;
  width: number;
  height: number;
  // MIGRATED: Replaces get_header_textcolor() / get_theme_support('custom-header') values
  header_text_color?: string;
  // MIGRATED: Replaces display_header_text()
  display_header_text?: boolean;
}

interface WordPressSiteSettings {
  title?: string;
  description?: string;
  // MIGRATED: Custom header image data from Customizer, exposed via REST settings endpoint
  header_image?: string;
  header_image_data?: WordPressHeaderImageData;
  header_textcolor?: string;
  // MIGRATED: Replaces display_header_text() — 'blank' hides text, any hex shows text
  header_text?: string;
}

interface CustomHeaderProps {
  // Allow passing pre-fetched settings to avoid redundant API calls
  settings?: WordPressSiteSettings;
}

// MIGRATED: Replaces _s_custom_header_setup() default values
// These constants mirror the add_theme_support('custom-header', [...]) args
const HEADER_DEFAULTS = {
  defaultImage: '',
  defaultTextColor: '000000',
  width: 1000,
  height: 250,
  flexHeight: true,
} as const;

// MIGRATED: Replaces get_header_textcolor() logic from _s_header_style()
// Returns null if text color is default (no custom styles needed),
// returns the hex color string if customized, or 'blank' if hidden.
function resolveHeaderTextColor(settings: WordPressSiteSettings | undefined): string | null {
  const textColor = settings?.header_textcolor;

  // MIGRATED: Mirrors: if (get_theme_support('custom-header', 'default-text-color') === $header_text_color) return;
  if (!textColor || textColor === HEADER_DEFAULTS.defaultTextColor) {
    return null;
  }

  return textColor;
}

// MIGRATED: Replaces display_header_text() check in _s_header_style()
// Returns true if the header text (site title + description) should be visible.
function shouldDisplayHeaderText(settings: WordPressSiteSettings | undefined): boolean {
  // MIGRATED: display_header_text() returns false when header_textcolor is 'blank'
  return settings?.header_text !== 'blank' && settings?.header_textcolor !== 'blank';
}

// MIGRATED: Replaces the inline <style> block generated by _s_header_style()
// Returns a CSSProperties object or className logic instead of injecting raw <style> tags.
// In WordPress, _s_header_style() echoed a <style> block into wp_head().
// Here we compute styles as React inline style objects.
function buildHeaderTextStyles(
  settings: WordPressSiteSettings | undefined
): {
  siteTextVisible: boolean;
  siteTextStyle: CSSProperties;
  hiddenTextStyle: CSSProperties;
} {
  const resolvedColor = resolveHeaderTextColor(settings);
  const displayText = shouldDisplayHeaderText(settings);

  // MIGRATED: Mirrors .site-title, .site-description { position: absolute; clip: rect(1px,1px,1px,1px); }
  // Accessibility-safe visually hidden pattern (replaces the CSS clip trick)
  const hiddenTextStyle: CSSProperties = {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  };

  // MIGRATED: Mirrors .site-title a, .site-description { color: #<?php echo esc_attr($header_text_color); ?>; }
  const siteTextStyle: CSSProperties =
    resolvedColor && displayText ? { color: `#${resolvedColor}` } : {};

  return {
    siteTextVisible: displayText,
    siteTextStyle,
    hiddenTextStyle,
  };
}

// MIGRATED: Replaces the_header_image_tag() template tag
// the_header_image_tag() outputs an <img> with the custom header image URL, width, height, and alt.
// Here we use Next.js <Image> with data fetched from the REST API.
function HeaderImage({
  settings,
}: {
  settings: WordPressSiteSettings | undefined;
}): JSX.Element | null {
  const imageUrl = settings?.header_image_data?.url || settings?.header_image || '';
  const width = settings?.header_image_data?.width ?? HEADER_DEFAULTS.width;
  const height = settings?.header_image_data?.height ?? HEADER_DEFAULTS.height;

  if (!imageUrl || imageUrl === 'remove-header') {
    return null;
  }

  return (
    // MIGRATED: Replaces the_header_image_tag() which output a plain <img>
    // Next.js <Image> provides automatic optimization, lazy loading, and responsive sizing
    // TODO: Manual review needed -- Ensure WordPress media domain is in next.config.js remotePatterns
    <Image
      src={imageUrl}
      alt="" // MIGRATED: WordPress custom header images are decorative; empty alt per WP core behavior
      width={width}
      height={height}
      priority // MIGRATED: Header image is above-the-fold; use priority loading (replaces WP's eager loading)
      style={{
        // MIGRATED: flex-height: true in add_theme_support allows variable height
        height: 'auto',
        width: '100%',
        maxWidth: `${HEADER_DEFAULTS.width}px`,
      }}
    />
  );
}

// MIGRATED: Main CustomHeader component
// Replaces: _s_custom_header_setup() + _s_header_style() + the_header_image_tag() in header.php
// Usage in Header.tsx or layout.tsx: <CustomHeader settings={siteSettings} />
export default function CustomHeader({ settings }: CustomHeaderProps): JSX.Element {
  const { siteTextVisible, siteTextStyle, hiddenTextStyle } = buildHeaderTextStyles(settings);

  const siteTitle = settings?.title ?? '';
  const siteDescription = settings?.description ?? '';

  return (
    <header className="site-header">
      {/* MIGRATED: Replaces the_header_image_tag() call in header.php */}
      <HeaderImage settings={settings} />

      <div className="site-branding">
        {/* MIGRATED: Replaces .site-title with conditional visibility
            Mirrors: if (!display_header_text()) apply visually-hidden CSS
            else apply custom color from get_header_textcolor() */}
        <p
          className="site-title"
          // MIGRATED: esc_html($siteTitle) -> JSX auto-escapes text content
          style={siteTextVisible ? siteTextStyle : hiddenTextStyle}
          aria-hidden={!siteTextVisible}
        >
          {siteTitle}
        </p>

        {/* MIGRATED: Replaces .site-description with same visibility logic */}
        <p
          className="site-description"
          style={siteTextVisible ? siteTextStyle : hiddenTextStyle}
          aria-hidden={!siteTextVisible}
        >
          {siteDescription}
        </p>
      </div>
    </header>
  );
}

// MIGRATED: Data fetching utility to replace Customizer API calls
// Replaces: get_header_textcolor(), display_header_text(), get_header_image(), get_header_image_tag()
// Call this in a Server Component (layout.tsx or Header.tsx) to pre-fetch settings.
// TODO: Manual review needed -- WordPress must expose header_image, header_textcolor, and
// header_text fields via /wp-json/wp/v2/settings (requires authentication) or a custom
// public REST endpoint. Without this, header customizations won't be reflected.
export async function fetchCustomHeaderSettings(
  siteUrl: string
): Promise<WordPressSiteSettings | null> {
  try {
    // MIGRATED: Replaces get_header_textcolor(), get_header_image_url(), bloginfo('name/description')
    // NOTE: /wp-json/wp/v2/settings requires authentication (edit_theme_options capability)
    // TODO: Manual review needed -- Create a public custom REST endpoint for safe header settings,
    // or hardcode defaults and manage via environment variables / Next.js config.
    const response = await fetch(`${siteUrl}/wp-json/wp/v2/settings`, {
      headers: {
        // TODO: Manual review needed -- Replace with actual auth mechanism (JWT or Application Password)
        // Authorization: `Bearer ${process.env.WP_API_TOKEN}`,
      },
      next: {
        // MIGRATED: ISR revalidation -- Customizer changes don't happen frequently
        revalidate: 3600, // Revalidate every hour
      },
    });

    if (!response.ok) {
      console.warn(
        `[CustomHeader] Failed to fetch WordPress settings: ${response.status} ${response.statusText}`
      );
      return null;
    }

    const settings: WordPressSiteSettings = await response.json();
    return settings;
  } catch (error) {
    console.error('[CustomHeader] Error fetching custom header settings:', error);
    return null;
  }
}

// MIGRATED: Export types for use in parent components (Header.tsx, layout.tsx)
export type { WordPressHeaderImageData, WordPressSiteSettings, CustomHeaderProps };